README.md, index.js, package-lock.json, views/recent.ejs, views/status.ejs
Hi FoxxMD
This is the frontend update I mentioned in #19 
It is intentionally basic, I havent added build tools/frontend framework in an attempt to keep this neat and tidy as this page needs to be clean clear and readable.
If you have any suggestions or changes you can think of let me know.
Again, thanks for putting the effort into this project and making it available to everyone.
=> Frontend update

views/status.ejs
Just a small update. Can wait till your next push of code for any features.
=> Feature: Fix padding on client box

index.js, views/status.ejs
- Removed fs watch as now it was running on my server I could see it was unreliable, if we can set up a middlewear for winston then we can remove the 10 second time out and rely on that instead
- Updated click events for the logging so that clicks now request fresh socket data and added basic fetch to set the level/limit/sort
=> feat: removed fs and made the options rely more on sockets

docs/plex.md
=> docs: tautulli payload duration => duration_sec [fixes #48]

docsite/docs/configuration/configuration.md
* Add missing 'backend' folder
* Change 'develop' branch to 'master'
Links have been tested locally just now. No automated test added.
Closes #122
=> Correct json-schema.app links

src/backend/sources/YTMusicSource.ts
=> Improve YTM experience

docsite/docs/FAQ.md
=> docs: fix link

src/backend/common/infrastructure/Atomic.ts, src/backend/sources/JellyfinApiSource.ts
SDK types say AlbumArtists etc. should be defined but #200 shows that's not always the case, for some reason.
Check for undefined value on playback data that requires additional transformation to prevent errors.
Fixes #200
=> fix(jellyfin): Gaurd against undefined playback data

Dockerfile
Fix the following warnings when building the Dockerfile:
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 60)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 89)
```
=> fix: fix WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match

docker-compose.yml
Removed version from `docker-compose.yml` which is obsolete and not used anymore.
=> fix: remove deprecated version from docker-compose.yml

src/backend/common/infrastructure/config/source/index.ts, src/backend/common/infrastructure/config/source/jellyfin.ts, src/backend/common/infrastructure/config/source/plex.ts, src/backend/common/logging.ts, src/backend/scrobblers/AbstractScrobbleClient.ts, src/backend/server/jellyfinRoutes.ts, src/backend/server/tautulliRoutes.ts, src/backend/sources/ChromecastSource.ts, src/backend/sources/JellyfinApiSource.ts, src/backend/sources/JellyfinSource.ts, src/backend/sources/PlexApiSource.ts, src/backend/utils.ts, src/backend/utils/NetworkUtils.ts
Finish implementation of debug mode behavior changes when using `DEBUG_MODE` env or `debugMode` from `config.json`
=> feat: Fully implement DEBUG_MODE

docsite/babel.config.js, docsite/docusaurus.config.ts, docsite/package-lock.json, docsite/package.json
=> docs: Update to Docusaurs 3.6 to improve build times

Dockerfile, package.json
Use `concurrently` during install and build to parallelize backend, frontend, and docs setup processes.
=> feat(docker): Paralellize npm install and build processes

README.md, config/azuracast.json.example, docsite/docs/configuration/configuration.mdx, docsite/src/pages/index.mdx, package-lock.json, src/backend/common/infrastructure/Atomic.ts, src/backend/common/infrastructure/config/source/azuracast.ts, src/backend/common/infrastructure/config/source/sources.ts, src/backend/common/vendor/azuracast/AzuracastApiClient.ts, src/backend/server/api.ts, src/backend/sources/AbstractSource.ts, src/backend/sources/AzuracastSource.ts, src/backend/sources/MusikcubeSource.ts, src/backend/sources/PlayerState/AzuracastPlayerState.ts, src/backend/sources/ScrobbleSources.ts, src/backend/utils/NetworkUtils.ts, src/client/components/statusCard/SourceStatusCard.tsx, src/client/components/statusCard/sourceDucks.ts, src/core/Atomic.ts
Adds [Azuracast](https://www.azuracast.com/) as a Source
#263
=> feat: Add Azuracast Source

src/backend/sources/JellyfinApiSource.ts
Parses musicbrainz metadata from jellyfin api payload
#297
=> feat(jellyfin): Add musicbrainz metadata #297

config/subsonic.json.example, docsite/docs/configuration/configuration.mdx, src/backend/common/infrastructure/config/source/subsonic.ts, src/backend/sources/SubsonicSource.ts
=> feat(subsonic): Implement filtering plays by user

docsite/docs/configuration/configuration.mdx, docsite/src/pages/index.mdx, src/backend/common/infrastructure/Atomic.ts, src/backend/common/infrastructure/config/client/index.ts, src/backend/common/infrastructure/config/client/lastfm.ts, src/backend/common/vendor/LastfmApiClient.ts, src/backend/scrobblers/AbstractScrobbleClient.ts, src/backend/scrobblers/LastfmScrobbler.ts, src/backend/scrobblers/ScrobbleClients.ts, src/backend/sources/MemorySource.ts, src/backend/tests/scrobbler/TestScrobbler.ts, src/backend/tests/scrobbler/scrobblers.test.ts, src/backend/tests/utils/PlayTestUtils.ts
Implements the Last.FM API for scrobbling the currently playing track.
The implementation is a *bit* crude, as we attempted to make the minimally needed changes. Feel free to reject the PR in this state, we just really wanted the feature to work already, and we're submitting the PR out of courtesy.
We've tested that it works on our machine:tm:, though there may be some potential issues with calling the API too often. We're also not ignoring duplicated scrobbles, as we wanted to make minimal changes.
We'll mark the PR as a draft PR for now, as we expect sure changes, since we're not very familiar with the codebase.
A few changes are just eslint being applied, feel free to ask to exclude those changes.
#164 (only the Last.FM part)
=> feat: lastfm nowplaying

config/koito.json.example, docsite/docs/configuration/configuration.mdx, docsite/docs/quickstart.mdx, docsite/src/pages/index.mdx, package-lock.json, package.json, src/backend/common/infrastructure/Atomic.ts, src/backend/common/infrastructure/config/client/clients.ts, src/backend/common/infrastructure/config/client/koito.ts, src/backend/common/infrastructure/config/source/koito.ts, src/backend/common/infrastructure/config/source/sources.ts, src/backend/common/vendor/ListenbrainzApiClient.ts, src/backend/common/vendor/koito/KoitoApiClient.ts, src/backend/scrobblers/KoitoScrobbler.ts, src/backend/scrobblers/ScrobbleClients.ts, src/backend/sources/DeezerInternalSource.ts, src/backend/sources/KoitoSource.ts, src/backend/sources/ScrobbleSources.ts, src/backend/utils/StringUtils.ts, src/core/StringUtils.ts
Implement full Koito Client and additional Source that are independent from Lisntebrainz implementation.
#300
=> Implement Koito Client/Source

docsite/docs/FAQ.md, src/backend/common/vendor/LastfmApiClient.ts, src/backend/common/vendor/ListenbrainzApiClient.ts
=> Lz album field

src/backend/common/infrastructure/Atomic.ts, src/backend/sources/PlayerState/AbstractPlayerState.ts, src/backend/tests/source/source.test.ts, src/backend/tests/utilitiesTests/time.test.ts, src/backend/utils/TimeUtils.ts
=> Repeat play detection improvements

config/maloja.json.example, docsite/docs/configuration/configuration.mdx, docsite/src/pages/index.mdx, src/backend/common/infrastructure/Atomic.ts, src/backend/common/infrastructure/config/client/maloja.ts, src/backend/common/infrastructure/config/source/maloja.ts, src/backend/common/infrastructure/config/source/sources.ts, src/backend/common/vendor/maloja/MalojaApiClient.ts, src/backend/common/vendor/maloja/interfaces.ts, src/backend/scrobblers/MalojaScrobbler.ts, src/backend/scrobblers/ScrobbleClients.ts, src/backend/sources/MalojaSource.ts, src/backend/sources/ScrobbleSources.ts, src/backend/utils.ts
* Move API code into own class for reusability with Source
* **Remove Maloja V2 compatibility**
* **Throw on connection if server version is too old or unknown**
* Implement Maloja Source
#295
=> feat: Add Maloja Source
