FoxxMD/multi-scrobbler

.github/workflows/dockerhub.yml

https://github.com/northys/multi-scrobbler/runs/6181049880
https://github.com/northys/multi-scrobbler/pkgs/container/multi-scrobbler
If you want I can change hash version of used actions to their major version but maloja owner required hashes for security and I saw that you used exact hash for docker login as well so I kept hash version in all actions.

build arm [closes #45]

---

sources/JellyfinSource.js

First off, thanks for all your work here! Tried the program out but noticed a couple of bugs when using a Jellyfin source, so I thought I'd take a crack at fixing them.
- User info was always empty from the webhook payload. The field  is `NotificationUsername` rather than `Username`
- Null reference error when trying to log an instance when the User info is undefined. The variable `hint` isn't defined here; wasn't sure what you wanted here as a hint, but for now I removed it to prevent errors!

Fix: Jellyfin source

---

docs/configuration.md

This is just based on my personal experience setting up `multi-scrobbler`, if I had 'Hide recent listening information' enabled I got errors about authentication 🤷🏾‍♂️.

Add note about privacy setting for Last.fm sources

---

src/backend/common/infrastructure/config/client/index.ts
src/backend/common/schema/aio-client.json
src/backend/common/schema/aio.json
src/backend/common/schema/client.json
src/backend/common/vendor/ListenbrainzApiClient.ts
src/backend/scrobblers/AbstractScrobbleClient.ts
src/backend/scrobblers/LastfmScrobbler.ts
src/backend/scrobblers/ListenbrainzScrobbler.ts
src/backend/scrobblers/MalojaScrobbler.ts
src/backend/tests/scrobbler/TestScrobbler.ts
src/backend/tests/scrobbler/scrobblers.test.ts

Changes to potentially address duplicate scrobble issues when client<-->source feedback loops occur #173 
~~Update scrobble config options to enable refreshing upstream service existing scrobbles in MS **on every scrobble** so that MS guarantees it always has the latest existing scrobbles to check for dups.~~
Force client to refresh scrobbled plays from upstream service if last refresh was at least X seconds ago
`listenbrainz.json` or another scrobble config
```diff
[
{
"name": "myScrobbler",
"data": {
// ...
},
+    "options": {
+      "refreshStaleAfter": 5
+    }
}
]
```

Enable more agressive scrobble checking behavior

---

src/backend/common/vendor/maloja/interfaces.ts
src/backend/scrobblers/AbstractScrobbleClient.ts
src/backend/scrobblers/MalojaScrobbler.ts
src/backend/tests/scrobbler/TestScrobbler.ts
src/backend/tests/scrobbler/scrobblers.test.ts

* Fixes incorrect handling for duplicate scrobble error from Maloja 3.2.2 #180
* More defensive Maloja scrobble parsing

fix(maloja): Improve handling for Maloja warnings-as-errors

---

config/jellyfin.json.example
docsite/docs/configuration/configuration.mdx
package-lock.json
package.json
src/backend/common/infrastructure/Atomic.ts
src/backend/common/infrastructure/config/source/jellyfin.ts
src/backend/common/infrastructure/config/source/sources.ts
src/backend/ioc.ts
src/backend/sources/JellyfinApiSource.ts
src/backend/sources/JellyfinSource.ts
src/backend/sources/ScrobbleSources.ts
src/backend/utils/StringUtils.ts

#171 
* :x: backlog implementation
* History items only indicate the track was played but not for how long (or that it was long enough to scrobble)
* :x: investigate "offline" scrobbling behavior #87
* Not possible at this time due to [JF api shortcomings](https://github.com/FoxxMD/multi-scrobbler/pull/172#issuecomment-2318553258)

feat: Refactor Jellyfin source to use Jellyfin API

---

docsite/docusaurus.config.ts

express-static prefers directories over files when using the extensions option, meaning an extensionless route will always route to the directory instead of the file (expressjs/serve-static#138). This causes URLs like http://localhost:9078/docs/docs/configuration to work when navigating from other pages (due to it being a SPA), but on reload it redirects to http://localhost:9078/docs/docs/configuration/ and returns a 404 (note the trailing slash).
This PR re-enables trailing slashes, which turns this structure:
```
docs
|- configuration
|  |- plex.html
|- configuration.html
```
Into:
```
docs
|- configuration
|- plex
|  |- index.html
|- index.html
```
This fixes local docs (served by the backend).
I've deployed it to GH pages here: https://jackwilsdon.github.io/multi-scrobbler/
All …

fix: local documentation

---

package-lock.json
package.json
src/backend/common/AbstractComponent.ts
src/backend/common/infrastructure/Atomic.ts
src/backend/common/infrastructure/config/client/index.ts
src/backend/common/infrastructure/config/common.ts
src/backend/common/infrastructure/config/source/index.ts
src/backend/common/schema/aio-client.json
src/backend/common/schema/aio-source.json
src/backend/common/schema/aio.json
src/backend/common/schema/client.json
src/backend/common/schema/source.json
src/backend/tests/component/component.test.ts
src/backend/utils.ts
src/backend/utils/PlayTransformUtils.ts

* Enables a user to have multiple if-then scenarios per hook

feat(modifications): Implement "when" conditions

---

.dockerignore
.gitignore
.mocharc.json
config/lastfm.json.example
config/listenbrainz.json.example
config/webscrobbler.json.example
package-lock.json
package.json
src/backend/common/infrastructure/Atomic.ts
src/backend/common/infrastructure/config/aioConfig.ts
src/backend/common/infrastructure/config/source/deezer.ts
src/backend/common/infrastructure/config/source/jellyfin.ts
src/backend/common/infrastructure/config/source/spotify.ts
src/backend/common/infrastructure/config/source/vlc.ts
src/backend/common/schema/aio-source.json
src/backend/common/schema/aio.json
src/backend/common/schema/source.json
src/backend/index.ts
src/backend/ioc.ts
src/backend/scrobblers/ScrobbleClients.ts
src/backend/sources/ScrobbleSources.ts
src/backend/tests/component/component.test.ts
src/backend/tests/config/config.test.ts
src/backend/tsconfig.json
src/backend/utils.ts
src/backend/utils/SchemaUtils.ts
src/backend/utils/ValidationUtils.ts
tsconfig.json

* Use runtime-generated schemas
* Ensures validated schemas always match code
* Can use schemas for individual source/clients without having to generate files
* catch individual validation errors and log instead of crashing
* refactor validation error output into chained error instead of as individual log statements to improve clarity
Will also fix the _crash_ from #199 but not the validation error.

feat: Improve client/source schema validation generation and error handling

---

config/plex.json.example
config/plex.webhook.json.example
docsite/docs/configuration/configuration.mdx
package-lock.json
package.json
src/backend/common/infrastructure/config/source/plex.ts
src/backend/common/infrastructure/config/source/sources.ts
src/backend/server/api.ts
src/backend/sources/PlayerState/AbstractPlayerState.ts
src/backend/sources/PlayerState/ListenRange.ts
src/backend/sources/PlayerState/PlexPlayerState.ts
src/backend/sources/PlayerState/RealtimePlayer.ts
src/backend/sources/PlexApiSource.ts
src/backend/sources/PlexSource.ts
src/backend/sources/ScrobbleSources.ts
src/backend/tests/plex/plex.test.ts
src/backend/tests/plex/validSession.json
src/backend/utils.ts

Implements a Source for Plex using the official API. This source will eventually replace the existing webhook Source.
Find a [**Plex Token**](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) for the Plex server and note the URL:PORT to use with it.
[Example file config](https://github.com/FoxxMD/multi-scrobbler/blob/plexApi/config/plex.json.example)
Example ENV config
| Environmental Variable | Required? | Default | Description                                                            |
| ---------------------- | --------- | ------- | ---------------------------------------------------------------------- |
| `PLEX_URL`             | **Yes**   |         | The URL of the Plex server IE …

feat(plex): Initial Plex API Source implementation

---

src/backend/common/infrastructure/Atomic.ts
src/backend/sources/ChromecastSource.ts
src/backend/sources/JRiverSource.ts
src/backend/sources/JellyfinApiSource.ts
src/backend/sources/KodiSource.ts
src/backend/sources/MPDSource.ts
src/backend/sources/MemoryPositionalSource.ts
src/backend/sources/MemorySource.ts
src/backend/sources/MopidySource.ts
src/backend/sources/MusikcubeSource.ts
src/backend/sources/PlayerState/AbstractPlayerState.ts
src/backend/sources/PlayerState/GenericPlayerState.ts
src/backend/sources/PlayerState/JellyfinPlayerState.ts
src/backend/sources/PlayerState/ListenProgress.ts
src/backend/sources/PlayerState/ListenRange.ts
src/backend/sources/PlayerState/PlexPlayerState.ts
src/backend/sources/PlayerState/PositionalPlayerState.ts
src/backend/sources/PlayerState/RealtimePlayer.ts
src/backend/sources/PlayerState/RealtimePlayerState.ts
src/backend/sources/PlexApiSource.ts
src/backend/sources/SpotifySource.ts
src/backend/sources/VLCSource.ts
src/backend/tests/player/player.test.ts
src/client/components/player/Player.tsx
src/client/components/player/PlayerTimestamp.tsx
src/client/components/player/timestamp.scss
src/core/Atomic.ts

* Introduce positional and non-positional data structures
* Refactor state player into types of each
* Refactor listen ranges and progress into types of each
* Implment (internal) real-time player and base positional player seeked/repeat on real-time drift instead of only reported position
* Refactor tests to use (emulated) real-time components
While this is a large fundamental restructure it (should) only functionally affect Plex API Source as it makes it more accurate since we don't rely solely on reported position for calculated state and listening range.
On the dev side it makes player state logic much clearer as there are way few if-else blocks just checking for `position === undefined`.

feat(player): Real time positional player state

---

docsite/docs/configuration/configuration.mdx
src/backend/sources/PlexApiSource.ts

* Identify when session is for the local user (no user is logged in)
* Add Local User as default allowed when no usersAllow settings
* Allow user config to allow/block local user
* Update plex docs
Fixes #218

fix(plex): Handle plex local user

---

config/ytmusic.json.example
docsite/docs/FAQ.md
docsite/docs/configuration/configuration.mdx
package-lock.json
package.json
src/backend/common/AbstractComponent.ts
src/backend/common/infrastructure/config/source/index.ts
src/backend/common/infrastructure/config/source/ytmusic.ts
src/backend/common/logging.ts
src/backend/index.ts
src/backend/ioc.ts
src/backend/server/auth.ts
src/backend/sources/AbstractSource.ts
src/backend/sources/ScrobbleSources.ts
src/backend/sources/YTMusicSource.ts

Youtube TV seems no longer have scope for reading history or account details. Cookies may work and custom oauth seems most stable based on reporting from LuanRT/YouTube.js#803
* Re-implement cookie auth
* Implement custom OAuth Client auth based on [example](https://github.com/LuanRT/YouTube.js/blob/main/examples/auth/custom-oauth2-creds/index.ts)
#195 
#229
#203

feat(ytm): Re-implement auth with cookie and oauth

---

src/backend/common/vendor/LastfmApiClient.ts
src/backend/ioc.ts
src/backend/notifier/AppriseWebhookNotifier.ts
src/backend/notifier/GotifyWebhookNotifier.ts
src/backend/notifier/NtfyWebhookNotifier.ts
src/backend/scrobblers/ScrobbleClients.ts
src/backend/server/index.ts
src/backend/sources/DeezerSource.ts
src/backend/sources/JellyfinApiSource.ts
src/backend/sources/PlexApiSource.ts
src/backend/sources/SpotifySource.ts
src/backend/sources/WebScrobblerSource.ts
src/backend/sources/YTMusicSource.ts
src/backend/tests/utils/strings.test.ts
src/backend/utils.ts
src/backend/utils/NetworkUtils.ts
src/core/Atomic.ts

* Notifications are not mission critical so its okay if they fail on init because service outage may be transient. Always init notification services and always attempt to push (we catch failures anyway)
* Parse more info from notification URL and test simple reachability of host/port to make troubleshooting easier
Fixes #215

feat(notifications): Make init more granular and always complete init

---

src/backend/common/AbstractComponent.ts
src/backend/common/errors/MSErrors.ts
src/backend/common/vendor/JRiverApiClient.ts
src/backend/common/vendor/KodiApiClient.ts
src/backend/index.ts
src/backend/scrobblers/AbstractScrobbleClient.ts
src/backend/scrobblers/MalojaScrobbler.ts
src/backend/server/api.ts
src/backend/server/auth.ts
src/backend/sources/AbstractSource.ts
src/backend/sources/DeezerSource.ts
src/backend/sources/JRiverSource.ts
src/backend/sources/KodiSource.ts
src/backend/tasks/heartbeatClients.ts
src/backend/tasks/heartbeatSources.ts
src/backend/tests/component/component.test.ts
src/backend/tests/scrobbler/scrobblers.test.ts
src/backend/utils.ts
src/backend/utils/ErrorUtils.ts
src/client/components/statusCard/ClientStatusCard.tsx
src/client/components/statusCard/SourceStatusCard.tsx
src/client/components/statusCard/StatusCardSkeleton.tsx
src/client/components/statusCard/sourceDucks.ts
src/client/store.ts

Need to refactor how `initialize()` is used so that is bubbles errors instead of just logging them. This way we can use the actual error reasons for `notify` or when user invokes API to show reasons for component not being able to recover. Needs work:
#220
#231

refactor: bubble init usage and errors to simplify recovery

---

src/backend/sources/MemorySource.ts
src/backend/sources/PlayerState/PlexPlayerState.ts
src/backend/sources/PlayerState/PositionalPlayerState.ts
src/backend/sources/PlexApiSource.ts

* Do play cleanup during polling for new plays so that we can discover tracks from abandoned players
* Fixes missed scrobbles from Plex API when Source stops returning a session due to player queue end
* Makes grace period for final range larger to compensate for plex api position coarseness (fixed non-100% listened scrobble)
#223

fix(plex): Improve handling of orphaned API sessions

---

src/backend/sources/AbstractSource.ts
src/backend/sources/YTMusicSource.ts
src/backend/tests/ytm/ytm.test.ts
src/backend/utils/PlayComparisonUtils.ts

* Use diff change type to restrict type of diff results allowed for YTM history changes -- only allow when add/bump diffs are prepend ("new" tracks at top of history list)
* Store some (4) recent history responses where order changed. Then, on add-prepend diffs check that a previous response does not exactly match. If it does this is probably an indicator a "newer" response actually has outdated data (#227) and we should ignore new tracks
* Add tests for YTM history processing to test all of the above
* Use shelf-playlist response instead of flat list when parsing plays so we preserve playlist name
* Print playlist name to diff debug for more context when troubleshooting logs
* Detect skipped plays based on reasonable time elapsed since last discovered track (#226)
* Newest track is …

fix(ytm): Improve history handling

---

.github/act/multiRunnerTest.yml
.github/workflows/pr.yml
.github/workflows/publishImage.yml

* Somewhat blocked by required release of ARM runners for public use
* https://github.com/github/roadmap/issues/970
* https://github.com/actions/runner-images/issues/10820
* https://github.com/orgs/community/discussions/142209#discussioncomment-11107737
* Until this is unblocked we need to keep QEMU step so performance is same as current build workflows
* Makes it easier for other users to fork and publish easily by only adding repo vars/secrets

Implement multi-runner image build for multi-arch improvements

---

src/backend/sources/MemorySource.ts

Add missing arg to pass to `getPlayedObject` to ensure the timestamp used for `playDate` is the same as normally discovered tracks. Without the arg two tracks played, with the latter being scrobbled on stale, would cause the latter to have the same TS as the former due to the former using end-of-play TS and the latter using first-seen-at TS (which would be the same)
#254

fix(spotify): Generate played object from cleanup with correct TS

---

package-lock.json
package.json
src/backend/common/infrastructure/config/common.ts
src/backend/sources/AbstractSource.ts
src/backend/sources/JellyfinSource.ts
src/backend/sources/MemorySource.ts
src/backend/sources/PlayerState/AbstractPlayerState.ts
src/backend/sources/PlayerState/PositionalPlayerState.ts
src/backend/sources/PlayerState/RealtimePlayer.ts
src/backend/tests/player/player.test.ts
src/backend/tests/source/TestSource.ts
src/backend/tests/source/source.test.ts
src/backend/tests/utils/PlayTestUtils.ts
src/backend/utils.ts
src/backend/utils/TimeUtils.ts

* Add user configurable stale/orphaned intervals
* Clear listening progress after scrobbling stale Play to prevent excess scrobbling if Play is resumed before player is orphaned
* Improve logging timestamps for activity and stale/orphaned statements

feat(source): Stale/orphan scrobble and timestamp improvments

---

README.md
config/musiccast.json.example
docsite/docs/configuration/configuration.mdx
docsite/src/pages/index.mdx
package-lock.json
package.json
src/backend/common/infrastructure/Atomic.ts
src/backend/common/infrastructure/config/source/musiccast.ts
src/backend/common/infrastructure/config/source/sources.ts
src/backend/sources/MemorySource.ts
src/backend/sources/MusicCastSource.ts
src/backend/sources/PlayerState/AbstractPlayerState.ts
src/backend/sources/PlayerState/PositionalPlayerState.ts
src/backend/sources/ScrobbleSources.ts
src/backend/tests/config/config.test.ts
src/backend/tests/musiccast/musiccast.test.ts
src/backend/tests/player/player.test.ts
src/backend/tests/source/source.test.ts
src/backend/utils.ts
src/backend/utils/NetworkUtils.ts

Add Yamaha MusicCast as a Source
#274

feat(musiccast): Implement MusicCast Source

---

src/backend/common/vendor/ListenbrainzApiClient.ts
src/backend/tests/listenbrainz/listenbrainz.test.ts

I added music_service_name field to the ListenBrainz submission payload. According to the [docs](https://listenbrainz.readthedocs.io/en/latest/users/json.html#id1) it's just a name to represents the service when there's no canonical domain. My reasoning behind this addition is that it would be nice to be able to identify the source of the scrobble even if it's not a know service name to Listenbrainz. I figured we could just use the multi-scrobbler source for that
Let me know if that works for you or if you have any thoughts/concerns :)

feat(listenbrainz): add source as music service name
